---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thedigiologist/domains/sajjadaliashar.com/public_html/
    - /bin/rsync -a --exclude='.git' --exclude='.next' ./ $DEPLOYPATH
    - cd $DEPLOYPATH && /usr/bin/npm ci
    - cd $DEPLOYPATH && /usr/bin/npm run build
